[package]
name = "spin-snowball-mapreverser"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

spin-snowball-shared = { path = "../shared" }