
[package]
name = "spin-snowball-shared"
version = "0.1.0"
edition = "2021"

[lib]
test = false

[dependencies]
serde = { version = "1.0", features = ["derive", "alloc"], default-features = false }
heapless = "0.8.0"